/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author bboteo
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMenuNuevo = new javax.swing.JButton();
        btnMenuMostrar = new javax.swing.JButton();
        btnMenuActualizar = new javax.swing.JButton();
        btnMenuEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BIBLIOTECA");

        btnMenuNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMenuNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mas.png"))); // NOI18N
        btnMenuNuevo.setText("Nuevo");
        btnMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuNuevoActionPerformed(evt);
            }
        });

        btnMenuMostrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMenuMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/buscar.png"))); // NOI18N
        btnMenuMostrar.setText("Mostrar");

        btnMenuActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMenuActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/configuraciones.png"))); // NOI18N
        btnMenuActualizar.setText("Actualizar");

        btnMenuEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMenuEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/menos.png"))); // NOI18N
        btnMenuEliminar.setText("Eliminar");
        btnMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnMenuActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMostrar)
                .addGap(18, 18, 18)
                .addComponent(btnMenuActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnMenuEliminar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuNuevoActionPerformed

    private void btnMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMenuActualizar;
    public javax.swing.JButton btnMenuEliminar;
    public javax.swing.JButton btnMenuMostrar;
    public javax.swing.JButton btnMenuNuevo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
