/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author bboteo
 */
public class FrmJugadorPrincipiante extends javax.swing.JFrame {

    /**
     * Creates new form FrmJugadorPrincipiante
     */
    public FrmJugadorPrincipiante() {
        initComponents();
        setIconImage(getIconImage());
    }

    //Icono del Jframe
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/quiz.png"));
        
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopPrincipianteMensaje = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnPrincipianteQ1 = new javax.swing.JPanel();
        lblPrincipianteQ1Peso = new javax.swing.JLabel();
        lblPrincipianteQ1Peso2 = new javax.swing.JLabel();
        scrPrincipianteQ1 = new javax.swing.JScrollPane();
        txaPrincipianteQ1Pregunta = new javax.swing.JTextArea();
        btnPrincipianteQ1Next = new javax.swing.JButton();
        txbPrincipianteQ1Res = new javax.swing.JTextField();
        lblPrincipianteQ1Res = new javax.swing.JLabel();
        jpnPrincipianteQ2 = new javax.swing.JPanel();
        lblPrincipianteQ2Peso1 = new javax.swing.JLabel();
        lblPrincipianteQ2Peso2 = new javax.swing.JLabel();
        scrPrincipianteQ2 = new javax.swing.JScrollPane();
        txaPrincipianteQ2Pregunta = new javax.swing.JTextArea();
        lblPrincipianteQ2Res = new javax.swing.JLabel();
        txbPrincipianteQ2Res = new javax.swing.JTextField();
        btnPrincipianteQ2Next = new javax.swing.JButton();
        jpnPrincipianteQ3 = new javax.swing.JPanel();
        lblPrincipianteQ3Peso1 = new javax.swing.JLabel();
        lblPrincipianteQ3Peso2 = new javax.swing.JLabel();
        scrPrincipianteQ3 = new javax.swing.JScrollPane();
        txaPrincipianteQ3Pregunta = new javax.swing.JTextArea();
        lblPrincipianteQ3Res = new javax.swing.JLabel();
        txbPrincipianteQ3Res = new javax.swing.JTextField();
        btnPrincipianteQ3Next = new javax.swing.JButton();
        jpnPrincipianteQ4 = new javax.swing.JPanel();
        lblPrincipianteQ4Peso1 = new javax.swing.JLabel();
        lblPrincipianteQ4Peso2 = new javax.swing.JLabel();
        scrPrincipianteQ4 = new javax.swing.JScrollPane();
        txaPrincipianteQ4Pregunta = new javax.swing.JTextArea();
        lblPrincipianteQ4Res = new javax.swing.JLabel();
        txbPrincipianteQ4Res = new javax.swing.JTextField();
        btnPrincipianteQ4Next = new javax.swing.JButton();
        jpnPrincipianteQ5 = new javax.swing.JPanel();
        lblPrincipianteQ5Peso1 = new javax.swing.JLabel();
        lblPrincipianteQ5Peso2 = new javax.swing.JLabel();
        scrPrincipianteQ5 = new javax.swing.JScrollPane();
        txaPrincipianteQ5Pregunta = new javax.swing.JTextArea();
        lblPrincipianteQ5Res = new javax.swing.JLabel();
        txbPrincipianteQ5Res = new javax.swing.JTextField();
        btnPrincipianteQ5Next = new javax.swing.JButton();
        jpnPrincipianteQ6 = new javax.swing.JPanel();
        lblPrincipianteQ6Peso1 = new javax.swing.JLabel();
        lblPrincipianteQ6Peso2 = new javax.swing.JLabel();
        scrPrincipianteQ6 = new javax.swing.JScrollPane();
        txaPrincipianteQ6Pregunta = new javax.swing.JTextArea();
        lblPrincipianteQ6Res = new javax.swing.JLabel();
        txbPrincipianteQ6Res = new javax.swing.JTextField();
        btnPrincipianteQ6End = new javax.swing.JButton();
        jpnPrincipianteCabecera = new javax.swing.JPanel();
        lblPrincipianteUsuario = new javax.swing.JLabel();
        lblPrincipianteIntento = new javax.swing.JLabel();
        txbPrincipianteDate = new javax.swing.JTextField();
        lblPrincipianteNivel = new javax.swing.JLabel();
        txbPrincipianteLv1 = new javax.swing.JTextField();
        txbPrincipianteLv2 = new javax.swing.JTextField();
        tbxPrincipianteLv3 = new javax.swing.JTextField();
        lblPrincipiantePuntos = new javax.swing.JLabel();
        txbPrincipiantePuntos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPrincipianteRepetir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txbPrincipianteIntentos = new javax.swing.JTextField();
        bproJugadorPrincipiante = new javax.swing.JProgressBar();
        btnPrincipianteSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jugador - Principiante");

        lblPrincipianteQ1Peso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ1Peso.setText("Peso:");

        lblPrincipianteQ1Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ1Peso2.setText("1/6");

        txaPrincipianteQ1Pregunta.setEditable(false);
        txaPrincipianteQ1Pregunta.setColumns(20);
        txaPrincipianteQ1Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaPrincipianteQ1Pregunta.setRows(5);
        scrPrincipianteQ1.setViewportView(txaPrincipianteQ1Pregunta);

        btnPrincipianteQ1Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteQ1Next.setText("Siguiente");

        txbPrincipianteQ1Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPrincipianteQ1Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ1Res.setText("Respuesta");

        javax.swing.GroupLayout jpnPrincipianteQ1Layout = new javax.swing.GroupLayout(jpnPrincipianteQ1);
        jpnPrincipianteQ1.setLayout(jpnPrincipianteQ1Layout);
        jpnPrincipianteQ1Layout.setHorizontalGroup(
            jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ1Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ1Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteQ1Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrincipianteQ1Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ1Layout.createSequentialGroup()
                        .addGroup(jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteQ1Peso)
                            .addComponent(lblPrincipianteQ1Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrPrincipianteQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnPrincipianteQ1Layout.setVerticalGroup(
            jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ1Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ1Peso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipianteQ1Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ1Layout.createSequentialGroup()
                        .addComponent(scrPrincipianteQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbPrincipianteQ1Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrincipianteQ1Res))
                    .addComponent(btnPrincipianteQ1Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1).", jpnPrincipianteQ1);

        lblPrincipianteQ2Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ2Peso1.setText("Peso:");

        lblPrincipianteQ2Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ2Peso2.setText("1/6");

        txaPrincipianteQ2Pregunta.setEditable(false);
        txaPrincipianteQ2Pregunta.setColumns(20);
        txaPrincipianteQ2Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaPrincipianteQ2Pregunta.setRows(5);
        scrPrincipianteQ2.setViewportView(txaPrincipianteQ2Pregunta);

        lblPrincipianteQ2Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ2Res.setText("Respuesta");

        txbPrincipianteQ2Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPrincipianteQ2Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteQ2Next.setText("Siguiente");

        javax.swing.GroupLayout jpnPrincipianteQ2Layout = new javax.swing.GroupLayout(jpnPrincipianteQ2);
        jpnPrincipianteQ2.setLayout(jpnPrincipianteQ2Layout);
        jpnPrincipianteQ2Layout.setHorizontalGroup(
            jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ2Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ2Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteQ2Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrincipianteQ2Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ2Layout.createSequentialGroup()
                        .addGroup(jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteQ2Peso1)
                            .addComponent(lblPrincipianteQ2Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrPrincipianteQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnPrincipianteQ2Layout.setVerticalGroup(
            jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ2Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ2Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipianteQ2Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ2Layout.createSequentialGroup()
                        .addComponent(scrPrincipianteQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbPrincipianteQ2Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrincipianteQ2Res))
                    .addComponent(btnPrincipianteQ2Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2).", jpnPrincipianteQ2);

        lblPrincipianteQ3Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ3Peso1.setText("Peso:");

        lblPrincipianteQ3Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ3Peso2.setText("1/6");

        txaPrincipianteQ3Pregunta.setEditable(false);
        txaPrincipianteQ3Pregunta.setColumns(20);
        txaPrincipianteQ3Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaPrincipianteQ3Pregunta.setRows(5);
        scrPrincipianteQ3.setViewportView(txaPrincipianteQ3Pregunta);

        lblPrincipianteQ3Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ3Res.setText("Respuesta");

        txbPrincipianteQ3Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPrincipianteQ3Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteQ3Next.setText("Siguiente");

        javax.swing.GroupLayout jpnPrincipianteQ3Layout = new javax.swing.GroupLayout(jpnPrincipianteQ3);
        jpnPrincipianteQ3.setLayout(jpnPrincipianteQ3Layout);
        jpnPrincipianteQ3Layout.setHorizontalGroup(
            jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ3Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ3Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteQ3Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrincipianteQ3Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ3Layout.createSequentialGroup()
                        .addGroup(jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteQ3Peso1)
                            .addComponent(lblPrincipianteQ3Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrPrincipianteQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnPrincipianteQ3Layout.setVerticalGroup(
            jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ3Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ3Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipianteQ3Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ3Layout.createSequentialGroup()
                        .addComponent(scrPrincipianteQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbPrincipianteQ3Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrincipianteQ3Res))
                    .addComponent(btnPrincipianteQ3Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3).", jpnPrincipianteQ3);

        lblPrincipianteQ4Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ4Peso1.setText("Peso:");

        lblPrincipianteQ4Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ4Peso2.setText("1/6");

        txaPrincipianteQ4Pregunta.setEditable(false);
        txaPrincipianteQ4Pregunta.setColumns(20);
        txaPrincipianteQ4Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaPrincipianteQ4Pregunta.setRows(5);
        scrPrincipianteQ4.setViewportView(txaPrincipianteQ4Pregunta);

        lblPrincipianteQ4Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ4Res.setText("Respuesta");

        txbPrincipianteQ4Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPrincipianteQ4Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteQ4Next.setText("Siguiente");

        javax.swing.GroupLayout jpnPrincipianteQ4Layout = new javax.swing.GroupLayout(jpnPrincipianteQ4);
        jpnPrincipianteQ4.setLayout(jpnPrincipianteQ4Layout);
        jpnPrincipianteQ4Layout.setHorizontalGroup(
            jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ4Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ4Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteQ4Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrincipianteQ4Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ4Layout.createSequentialGroup()
                        .addGroup(jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteQ4Peso1)
                            .addComponent(lblPrincipianteQ4Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrPrincipianteQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnPrincipianteQ4Layout.setVerticalGroup(
            jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ4Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ4Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipianteQ4Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ4Layout.createSequentialGroup()
                        .addComponent(scrPrincipianteQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbPrincipianteQ4Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrincipianteQ4Res))
                    .addComponent(btnPrincipianteQ4Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4).", jpnPrincipianteQ4);

        lblPrincipianteQ5Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ5Peso1.setText("Peso:");

        lblPrincipianteQ5Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ5Peso2.setText("1/6");

        txaPrincipianteQ5Pregunta.setEditable(false);
        txaPrincipianteQ5Pregunta.setColumns(20);
        txaPrincipianteQ5Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaPrincipianteQ5Pregunta.setRows(5);
        scrPrincipianteQ5.setViewportView(txaPrincipianteQ5Pregunta);

        lblPrincipianteQ5Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ5Res.setText("Respuesta");

        txbPrincipianteQ5Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPrincipianteQ5Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteQ5Next.setText("Siguiente");

        javax.swing.GroupLayout jpnPrincipianteQ5Layout = new javax.swing.GroupLayout(jpnPrincipianteQ5);
        jpnPrincipianteQ5.setLayout(jpnPrincipianteQ5Layout);
        jpnPrincipianteQ5Layout.setHorizontalGroup(
            jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ5Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ5Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteQ5Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrincipianteQ5Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ5Layout.createSequentialGroup()
                        .addGroup(jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteQ5Peso1)
                            .addComponent(lblPrincipianteQ5Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrPrincipianteQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnPrincipianteQ5Layout.setVerticalGroup(
            jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ5Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ5Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipianteQ5Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ5Layout.createSequentialGroup()
                        .addComponent(scrPrincipianteQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbPrincipianteQ5Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrincipianteQ5Res))
                    .addComponent(btnPrincipianteQ5Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("5).", jpnPrincipianteQ5);

        lblPrincipianteQ6Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ6Peso1.setText("Peso:");

        lblPrincipianteQ6Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ6Peso2.setText("1/6");

        txaPrincipianteQ6Pregunta.setEditable(false);
        txaPrincipianteQ6Pregunta.setColumns(20);
        txaPrincipianteQ6Pregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaPrincipianteQ6Pregunta.setRows(5);
        scrPrincipianteQ6.setViewportView(txaPrincipianteQ6Pregunta);

        lblPrincipianteQ6Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrincipianteQ6Res.setText("Respuesta");

        txbPrincipianteQ6Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPrincipianteQ6End.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteQ6End.setText("Finalizar");

        javax.swing.GroupLayout jpnPrincipianteQ6Layout = new javax.swing.GroupLayout(jpnPrincipianteQ6);
        jpnPrincipianteQ6.setLayout(jpnPrincipianteQ6Layout);
        jpnPrincipianteQ6Layout.setHorizontalGroup(
            jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnPrincipianteQ6Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ6Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteQ6Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrincipianteQ6End, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPrincipianteQ6Layout.createSequentialGroup()
                        .addGroup(jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteQ6Peso1)
                            .addComponent(lblPrincipianteQ6Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrPrincipianteQ6, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnPrincipianteQ6Layout.setVerticalGroup(
            jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteQ6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ6Layout.createSequentialGroup()
                        .addComponent(lblPrincipianteQ6Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipianteQ6Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteQ6Layout.createSequentialGroup()
                        .addComponent(scrPrincipianteQ6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbPrincipianteQ6Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrincipianteQ6Res))
                    .addComponent(btnPrincipianteQ6End))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("6).", jpnPrincipianteQ6);

        lblPrincipianteUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrincipianteUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lblPrincipianteUsuario.setText("Usuario:");

        lblPrincipianteIntento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrincipianteIntento.setForeground(new java.awt.Color(153, 153, 153));
        lblPrincipianteIntento.setText("Ultimo Intento:");

        txbPrincipianteDate.setEditable(false);
        txbPrincipianteDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbPrincipianteDate.setForeground(new java.awt.Color(153, 153, 153));
        txbPrincipianteDate.setText("dd-mm-yyy, hh:mm");

        lblPrincipianteNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrincipianteNivel.setText("Nivel Actual: Principiante");

        txbPrincipianteLv1.setEditable(false);
        txbPrincipianteLv1.setBackground(new java.awt.Color(255, 255, 0));
        txbPrincipianteLv1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbPrincipianteLv1.setText("          ");
        txbPrincipianteLv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbPrincipianteLv1ActionPerformed(evt);
            }
        });

        txbPrincipianteLv2.setEditable(false);
        txbPrincipianteLv2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbPrincipianteLv2.setText("          ");
        txbPrincipianteLv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbPrincipianteLv2ActionPerformed(evt);
            }
        });

        tbxPrincipianteLv3.setEditable(false);
        tbxPrincipianteLv3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbxPrincipianteLv3.setText("          ");
        tbxPrincipianteLv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxPrincipianteLv3ActionPerformed(evt);
            }
        });

        lblPrincipiantePuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrincipiantePuntos.setText("Ultima Puntuacion");

        txbPrincipiantePuntos.setEditable(false);
        txbPrincipiantePuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbPrincipiantePuntos.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Intentos");

        btnPrincipianteRepetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sincronizar.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Reiniciar la Prueba");

        txbPrincipianteIntentos.setEditable(false);
        txbPrincipianteIntentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbPrincipianteIntentos.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jpnPrincipianteCabeceraLayout = new javax.swing.GroupLayout(jpnPrincipianteCabecera);
        jpnPrincipianteCabecera.setLayout(jpnPrincipianteCabeceraLayout);
        jpnPrincipianteCabeceraLayout.setHorizontalGroup(
            jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipianteCabeceraLayout.createSequentialGroup()
                        .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipianteUsuario)
                            .addComponent(lblPrincipianteIntento))
                        .addGap(18, 18, 18)
                        .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrincipianteNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txbPrincipianteDate)))
                    .addGroup(jpnPrincipianteCabeceraLayout.createSequentialGroup()
                        .addComponent(btnPrincipianteRepetir)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(55, 55, 55)
                .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteCabeceraLayout.createSequentialGroup()
                        .addComponent(txbPrincipianteLv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txbPrincipianteLv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbxPrincipianteLv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPrincipianteCabeceraLayout.createSequentialGroup()
                        .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrincipiantePuntos)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbPrincipianteIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txbPrincipiantePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnPrincipianteCabeceraLayout.setVerticalGroup(
            jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipianteCabeceraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrincipianteUsuario)
                    .addComponent(lblPrincipianteNivel)
                    .addComponent(txbPrincipianteLv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbPrincipianteLv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxPrincipianteLv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrincipianteIntento)
                    .addComponent(txbPrincipianteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrincipiantePuntos)
                    .addComponent(txbPrincipiantePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrincipianteRepetir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipianteCabeceraLayout.createSequentialGroup()
                        .addGroup(jpnPrincipianteCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txbPrincipianteIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        bproJugadorPrincipiante.setBackground(new java.awt.Color(255, 255, 255));
        bproJugadorPrincipiante.setForeground(new java.awt.Color(255, 255, 0));

        btnPrincipianteSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipianteSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salida.png"))); // NOI18N
        btnPrincipianteSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bproJugadorPrincipiante, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrincipianteSalir)
                        .addGap(8, 8, 8))
                    .addComponent(jpnPrincipianteCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnPrincipianteCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(bproJugadorPrincipiante, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrincipianteSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbPrincipianteLv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbPrincipianteLv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbPrincipianteLv1ActionPerformed

    private void txbPrincipianteLv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbPrincipianteLv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbPrincipianteLv2ActionPerformed

    private void tbxPrincipianteLv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxPrincipianteLv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxPrincipianteLv3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJugadorPrincipiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar bproJugadorPrincipiante;
    public javax.swing.JButton btnPrincipianteQ1Next;
    public javax.swing.JButton btnPrincipianteQ2Next;
    public javax.swing.JButton btnPrincipianteQ3Next;
    public javax.swing.JButton btnPrincipianteQ4Next;
    public javax.swing.JButton btnPrincipianteQ5Next;
    public javax.swing.JButton btnPrincipianteQ6End;
    public javax.swing.JButton btnPrincipianteRepetir;
    public javax.swing.JButton btnPrincipianteSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JOptionPane jopPrincipianteMensaje;
    private javax.swing.JPanel jpnPrincipianteCabecera;
    public javax.swing.JPanel jpnPrincipianteQ1;
    public javax.swing.JPanel jpnPrincipianteQ2;
    public javax.swing.JPanel jpnPrincipianteQ3;
    public javax.swing.JPanel jpnPrincipianteQ4;
    public javax.swing.JPanel jpnPrincipianteQ5;
    public javax.swing.JPanel jpnPrincipianteQ6;
    private javax.swing.JLabel lblPrincipianteIntento;
    private javax.swing.JLabel lblPrincipianteNivel;
    private javax.swing.JLabel lblPrincipiantePuntos;
    private javax.swing.JLabel lblPrincipianteQ1Peso;
    private javax.swing.JLabel lblPrincipianteQ1Peso2;
    private javax.swing.JLabel lblPrincipianteQ1Res;
    private javax.swing.JLabel lblPrincipianteQ2Peso1;
    private javax.swing.JLabel lblPrincipianteQ2Peso2;
    private javax.swing.JLabel lblPrincipianteQ2Res;
    private javax.swing.JLabel lblPrincipianteQ3Peso1;
    private javax.swing.JLabel lblPrincipianteQ3Peso2;
    private javax.swing.JLabel lblPrincipianteQ3Res;
    private javax.swing.JLabel lblPrincipianteQ4Peso1;
    private javax.swing.JLabel lblPrincipianteQ4Peso2;
    private javax.swing.JLabel lblPrincipianteQ4Res;
    private javax.swing.JLabel lblPrincipianteQ5Peso1;
    private javax.swing.JLabel lblPrincipianteQ5Peso2;
    private javax.swing.JLabel lblPrincipianteQ5Res;
    private javax.swing.JLabel lblPrincipianteQ6Peso1;
    private javax.swing.JLabel lblPrincipianteQ6Peso2;
    private javax.swing.JLabel lblPrincipianteQ6Res;
    public javax.swing.JLabel lblPrincipianteUsuario;
    public javax.swing.JScrollPane scrPrincipianteQ1;
    public javax.swing.JScrollPane scrPrincipianteQ2;
    public javax.swing.JScrollPane scrPrincipianteQ3;
    public javax.swing.JScrollPane scrPrincipianteQ4;
    public javax.swing.JScrollPane scrPrincipianteQ5;
    public javax.swing.JScrollPane scrPrincipianteQ6;
    public javax.swing.JTextField tbxPrincipianteLv3;
    public javax.swing.JTextArea txaPrincipianteQ1Pregunta;
    public javax.swing.JTextArea txaPrincipianteQ2Pregunta;
    public javax.swing.JTextArea txaPrincipianteQ3Pregunta;
    public javax.swing.JTextArea txaPrincipianteQ4Pregunta;
    public javax.swing.JTextArea txaPrincipianteQ5Pregunta;
    public javax.swing.JTextArea txaPrincipianteQ6Pregunta;
    public javax.swing.JTextField txbPrincipianteDate;
    public javax.swing.JTextField txbPrincipianteIntentos;
    public javax.swing.JTextField txbPrincipianteLv1;
    public javax.swing.JTextField txbPrincipianteLv2;
    public javax.swing.JTextField txbPrincipiantePuntos;
    public javax.swing.JTextField txbPrincipianteQ1Res;
    public javax.swing.JTextField txbPrincipianteQ2Res;
    public javax.swing.JTextField txbPrincipianteQ3Res;
    public javax.swing.JTextField txbPrincipianteQ4Res;
    public javax.swing.JTextField txbPrincipianteQ5Res;
    public javax.swing.JTextField txbPrincipianteQ6Res;
    // End of variables declaration//GEN-END:variables
}
