/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author bboteo
 */
public class FrmJugadorAvanzado extends javax.swing.JFrame {

    /**
     * Creates new form FrmJugadorPrincipiante
     */
    public FrmJugadorAvanzado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopAvanzadoMensaje = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnAvanzadoQ1 = new javax.swing.JPanel();
        lblAvanzadoQ1Peso = new javax.swing.JLabel();
        lblAvanzadoQ1Peso2 = new javax.swing.JLabel();
        scrAvanzadoQ1 = new javax.swing.JScrollPane();
        txaAvanzadoQ1Pregunta = new javax.swing.JTextArea();
        btnAvanzadoQ1Next = new javax.swing.JButton();
        txbAvanzadoQ1Res = new javax.swing.JTextField();
        lblAvanzadoQ1Res = new javax.swing.JLabel();
        jpnAvanzadoQ2 = new javax.swing.JPanel();
        lbAvanzadoQ2Peso1 = new javax.swing.JLabel();
        lblAvanzadoQ2Peso2 = new javax.swing.JLabel();
        scrAvanzadoQ2 = new javax.swing.JScrollPane();
        txaAvanzadoQ2Pregunta = new javax.swing.JTextArea();
        lblAvanzadoQ2Res = new javax.swing.JLabel();
        txbAvanzadoQ2Res = new javax.swing.JTextField();
        btnAvanzadoQ2Next1 = new javax.swing.JButton();
        jpnAvanzadoQ3 = new javax.swing.JPanel();
        lblAvanzadoQ3Peso1 = new javax.swing.JLabel();
        lblAvanzadoQ3Peso2 = new javax.swing.JLabel();
        scrAvanzadoQ3 = new javax.swing.JScrollPane();
        txaAvanzadoQ3Pregunta = new javax.swing.JTextArea();
        lblAvanzadoQ3Res = new javax.swing.JLabel();
        txbAvanzadoQ3Res = new javax.swing.JTextField();
        btnAvanzadoQ3Next2 = new javax.swing.JButton();
        jpnAvanzadoQ4 = new javax.swing.JPanel();
        lblAvanzadoQ4Peso1 = new javax.swing.JLabel();
        lblAvanzadoQ4Peso2 = new javax.swing.JLabel();
        scrAvanzadoQ4 = new javax.swing.JScrollPane();
        txaAvanzadoQ4Pregunta = new javax.swing.JTextArea();
        lblAvanzadoQ4Res = new javax.swing.JLabel();
        txbAvanzadoQ4Res = new javax.swing.JTextField();
        btnAvanzadoQ4Next = new javax.swing.JButton();
        jpnAvanzadoCabecera = new javax.swing.JPanel();
        lblAvanzadoUsuario = new javax.swing.JLabel();
        lblAvanzadoIntento = new javax.swing.JLabel();
        txbAvanzadoDate = new javax.swing.JTextField();
        lblAvanzadoNivel = new javax.swing.JLabel();
        txbAvanzadoLv1 = new javax.swing.JTextField();
        txbAvanzadoLv2 = new javax.swing.JTextField();
        tbxAvanzadoLv3 = new javax.swing.JTextField();
        lblAvanzadoPuntos = new javax.swing.JLabel();
        txbAvanzadoPuntos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jugador - Principiante");

        lblAvanzadoQ1Peso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ1Peso.setText("Peso:");

        lblAvanzadoQ1Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ1Peso2.setText("1/6");

        txaAvanzadoQ1Pregunta.setEditable(false);
        txaAvanzadoQ1Pregunta.setColumns(20);
        txaAvanzadoQ1Pregunta.setRows(5);
        scrAvanzadoQ1.setViewportView(txaAvanzadoQ1Pregunta);

        btnAvanzadoQ1Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzadoQ1Next.setText("Siguiente");

        txbAvanzadoQ1Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblAvanzadoQ1Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ1Res.setText("Respuesta");

        javax.swing.GroupLayout jpnAvanzadoQ1Layout = new javax.swing.GroupLayout(jpnAvanzadoQ1);
        jpnAvanzadoQ1.setLayout(jpnAvanzadoQ1Layout);
        jpnAvanzadoQ1Layout.setHorizontalGroup(
            jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ1Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ1Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbAvanzadoQ1Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvanzadoQ1Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ1Layout.createSequentialGroup()
                        .addGroup(jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvanzadoQ1Peso)
                            .addComponent(lblAvanzadoQ1Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrAvanzadoQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnAvanzadoQ1Layout.setVerticalGroup(
            jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ1Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ1Peso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvanzadoQ1Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ1Layout.createSequentialGroup()
                        .addComponent(scrAvanzadoQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbAvanzadoQ1Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvanzadoQ1Res))
                    .addComponent(btnAvanzadoQ1Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1).", jpnAvanzadoQ1);

        lbAvanzadoQ2Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbAvanzadoQ2Peso1.setText("Peso:");

        lblAvanzadoQ2Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ2Peso2.setText("1/6");

        txaAvanzadoQ2Pregunta.setEditable(false);
        txaAvanzadoQ2Pregunta.setColumns(20);
        txaAvanzadoQ2Pregunta.setRows(5);
        scrAvanzadoQ2.setViewportView(txaAvanzadoQ2Pregunta);

        lblAvanzadoQ2Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ2Res.setText("Respuesta");

        txbAvanzadoQ2Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAvanzadoQ2Next1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzadoQ2Next1.setText("Siguiente");

        javax.swing.GroupLayout jpnAvanzadoQ2Layout = new javax.swing.GroupLayout(jpnAvanzadoQ2);
        jpnAvanzadoQ2.setLayout(jpnAvanzadoQ2Layout);
        jpnAvanzadoQ2Layout.setHorizontalGroup(
            jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ2Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ2Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbAvanzadoQ2Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvanzadoQ2Next1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ2Layout.createSequentialGroup()
                        .addGroup(jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAvanzadoQ2Peso1)
                            .addComponent(lblAvanzadoQ2Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrAvanzadoQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnAvanzadoQ2Layout.setVerticalGroup(
            jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ2Layout.createSequentialGroup()
                        .addComponent(lbAvanzadoQ2Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvanzadoQ2Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ2Layout.createSequentialGroup()
                        .addComponent(scrAvanzadoQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbAvanzadoQ2Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvanzadoQ2Res))
                    .addComponent(btnAvanzadoQ2Next1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2).", jpnAvanzadoQ2);

        lblAvanzadoQ3Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ3Peso1.setText("Peso:");

        lblAvanzadoQ3Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ3Peso2.setText("1/6");

        txaAvanzadoQ3Pregunta.setEditable(false);
        txaAvanzadoQ3Pregunta.setColumns(20);
        txaAvanzadoQ3Pregunta.setRows(5);
        scrAvanzadoQ3.setViewportView(txaAvanzadoQ3Pregunta);

        lblAvanzadoQ3Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ3Res.setText("Respuesta");

        txbAvanzadoQ3Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAvanzadoQ3Next2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzadoQ3Next2.setText("Siguiente");

        javax.swing.GroupLayout jpnAvanzadoQ3Layout = new javax.swing.GroupLayout(jpnAvanzadoQ3);
        jpnAvanzadoQ3.setLayout(jpnAvanzadoQ3Layout);
        jpnAvanzadoQ3Layout.setHorizontalGroup(
            jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ3Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ3Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbAvanzadoQ3Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvanzadoQ3Next2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ3Layout.createSequentialGroup()
                        .addGroup(jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvanzadoQ3Peso1)
                            .addComponent(lblAvanzadoQ3Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrAvanzadoQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnAvanzadoQ3Layout.setVerticalGroup(
            jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ3Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ3Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvanzadoQ3Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ3Layout.createSequentialGroup()
                        .addComponent(scrAvanzadoQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbAvanzadoQ3Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvanzadoQ3Res))
                    .addComponent(btnAvanzadoQ3Next2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3).", jpnAvanzadoQ3);

        lblAvanzadoQ4Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ4Peso1.setText("Peso:");

        lblAvanzadoQ4Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ4Peso2.setText("1/6");

        txaAvanzadoQ4Pregunta.setEditable(false);
        txaAvanzadoQ4Pregunta.setColumns(20);
        txaAvanzadoQ4Pregunta.setRows(5);
        scrAvanzadoQ4.setViewportView(txaAvanzadoQ4Pregunta);

        lblAvanzadoQ4Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvanzadoQ4Res.setText("Respuesta");

        txbAvanzadoQ4Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAvanzadoQ4Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzadoQ4Next.setText("Siguiente");

        javax.swing.GroupLayout jpnAvanzadoQ4Layout = new javax.swing.GroupLayout(jpnAvanzadoQ4);
        jpnAvanzadoQ4.setLayout(jpnAvanzadoQ4Layout);
        jpnAvanzadoQ4Layout.setHorizontalGroup(
            jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ4Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ4Res)
                        .addGap(18, 18, 18)
                        .addComponent(txbAvanzadoQ4Res, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvanzadoQ4Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ4Layout.createSequentialGroup()
                        .addGroup(jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvanzadoQ4Peso1)
                            .addComponent(lblAvanzadoQ4Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrAvanzadoQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnAvanzadoQ4Layout.setVerticalGroup(
            jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoQ4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ4Layout.createSequentialGroup()
                        .addComponent(lblAvanzadoQ4Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvanzadoQ4Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoQ4Layout.createSequentialGroup()
                        .addComponent(scrAvanzadoQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAvanzadoQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbAvanzadoQ4Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvanzadoQ4Res))
                    .addComponent(btnAvanzadoQ4Next))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4).", jpnAvanzadoQ4);

        lblAvanzadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvanzadoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lblAvanzadoUsuario.setText("Usuario: bboteo");

        lblAvanzadoIntento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvanzadoIntento.setForeground(new java.awt.Color(153, 153, 153));
        lblAvanzadoIntento.setText("Ultimo Intento:");

        txbAvanzadoDate.setEditable(false);
        txbAvanzadoDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbAvanzadoDate.setForeground(new java.awt.Color(153, 153, 153));
        txbAvanzadoDate.setText("dd-mm-yyy, hh:mm");

        lblAvanzadoNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvanzadoNivel.setText("Nivel Actual: Avanzado");

        txbAvanzadoLv1.setEditable(false);
        txbAvanzadoLv1.setBackground(new java.awt.Color(255, 255, 0));
        txbAvanzadoLv1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbAvanzadoLv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbAvanzadoLv1ActionPerformed(evt);
            }
        });

        txbAvanzadoLv2.setEditable(false);
        txbAvanzadoLv2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbAvanzadoLv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbAvanzadoLv2ActionPerformed(evt);
            }
        });

        tbxAvanzadoLv3.setEditable(false);
        tbxAvanzadoLv3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbxAvanzadoLv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxAvanzadoLv3ActionPerformed(evt);
            }
        });

        lblAvanzadoPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvanzadoPuntos.setText("Ultima Puntuacion");

        txbAvanzadoPuntos.setEditable(false);
        txbAvanzadoPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbAvanzadoPuntos.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jpnAvanzadoCabeceraLayout = new javax.swing.GroupLayout(jpnAvanzadoCabecera);
        jpnAvanzadoCabecera.setLayout(jpnAvanzadoCabeceraLayout);
        jpnAvanzadoCabeceraLayout.setHorizontalGroup(
            jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvanzadoUsuario)
                    .addComponent(lblAvanzadoIntento))
                .addGap(18, 18, 18)
                .addGroup(jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvanzadoNivel)
                    .addComponent(txbAvanzadoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAvanzadoCabeceraLayout.createSequentialGroup()
                        .addComponent(txbAvanzadoLv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txbAvanzadoLv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbxAvanzadoLv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnAvanzadoCabeceraLayout.createSequentialGroup()
                        .addComponent(lblAvanzadoPuntos)
                        .addGap(18, 18, 18)
                        .addComponent(txbAvanzadoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnAvanzadoCabeceraLayout.setVerticalGroup(
            jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAvanzadoCabeceraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvanzadoUsuario)
                    .addComponent(lblAvanzadoNivel)
                    .addComponent(txbAvanzadoLv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbAvanzadoLv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxAvanzadoLv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnAvanzadoCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvanzadoIntento)
                    .addComponent(txbAvanzadoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvanzadoPuntos)
                    .addComponent(txbAvanzadoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnAvanzadoCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnAvanzadoCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbAvanzadoLv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbAvanzadoLv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbAvanzadoLv1ActionPerformed

    private void txbAvanzadoLv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbAvanzadoLv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbAvanzadoLv2ActionPerformed

    private void tbxAvanzadoLv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxAvanzadoLv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxAvanzadoLv3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJugadorAvanzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAvanzadoQ1Next;
    public javax.swing.JButton btnAvanzadoQ2Next1;
    public javax.swing.JButton btnAvanzadoQ3Next2;
    public javax.swing.JButton btnAvanzadoQ4Next;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JOptionPane jopAvanzadoMensaje;
    private javax.swing.JPanel jpnAvanzadoCabecera;
    public javax.swing.JPanel jpnAvanzadoQ1;
    public javax.swing.JPanel jpnAvanzadoQ2;
    public javax.swing.JPanel jpnAvanzadoQ3;
    public javax.swing.JPanel jpnAvanzadoQ4;
    private javax.swing.JLabel lbAvanzadoQ2Peso1;
    private javax.swing.JLabel lblAvanzadoIntento;
    private javax.swing.JLabel lblAvanzadoNivel;
    private javax.swing.JLabel lblAvanzadoPuntos;
    private javax.swing.JLabel lblAvanzadoQ1Peso;
    private javax.swing.JLabel lblAvanzadoQ1Peso2;
    private javax.swing.JLabel lblAvanzadoQ1Res;
    private javax.swing.JLabel lblAvanzadoQ2Peso2;
    private javax.swing.JLabel lblAvanzadoQ2Res;
    private javax.swing.JLabel lblAvanzadoQ3Peso1;
    private javax.swing.JLabel lblAvanzadoQ3Peso2;
    private javax.swing.JLabel lblAvanzadoQ3Res;
    private javax.swing.JLabel lblAvanzadoQ4Peso1;
    private javax.swing.JLabel lblAvanzadoQ4Peso2;
    private javax.swing.JLabel lblAvanzadoQ4Res;
    private javax.swing.JLabel lblAvanzadoUsuario;
    public javax.swing.JScrollPane scrAvanzadoQ1;
    public javax.swing.JScrollPane scrAvanzadoQ2;
    public javax.swing.JScrollPane scrAvanzadoQ3;
    public javax.swing.JScrollPane scrAvanzadoQ4;
    public javax.swing.JTextField tbxAvanzadoLv3;
    public javax.swing.JTextArea txaAvanzadoQ1Pregunta;
    public javax.swing.JTextArea txaAvanzadoQ2Pregunta;
    public javax.swing.JTextArea txaAvanzadoQ3Pregunta;
    public javax.swing.JTextArea txaAvanzadoQ4Pregunta;
    public javax.swing.JTextField txbAvanzadoDate;
    public javax.swing.JTextField txbAvanzadoLv1;
    public javax.swing.JTextField txbAvanzadoLv2;
    public javax.swing.JTextField txbAvanzadoPuntos;
    public javax.swing.JTextField txbAvanzadoQ1Res;
    public javax.swing.JTextField txbAvanzadoQ2Res;
    public javax.swing.JTextField txbAvanzadoQ3Res;
    public javax.swing.JTextField txbAvanzadoQ4Res;
    // End of variables declaration//GEN-END:variables
}
