/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author bboteo
 */
public class FrmJugadorIntermedio extends javax.swing.JFrame {

    /**
     * Creates new form FrmJugadorPrincipiante
     */
    public FrmJugadorIntermedio() {
        initComponents();
        setIconImage(getIconImage());
    }
    //Icono del Jframe
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/quiz.png"));
        
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopIntermedioMensaje = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnIntermedioQ1 = new javax.swing.JPanel();
        lblIntermedioeQ1Peso = new javax.swing.JLabel();
        lblIntermedioQ1Peso2 = new javax.swing.JLabel();
        scrIntermedioQ1 = new javax.swing.JScrollPane();
        txaIntermedioQ1Pregunta = new javax.swing.JTextArea();
        btnIntermedioQ1Next = new javax.swing.JButton();
        lblIntermedioQ1Res = new javax.swing.JLabel();
        jcbIntermedioQ1Res = new javax.swing.JComboBox<>();
        jpnIntermedioQ2 = new javax.swing.JPanel();
        lblIntermedioQ2Peso1 = new javax.swing.JLabel();
        lblIntermedioQ2Peso2 = new javax.swing.JLabel();
        scrIntermedioQ2 = new javax.swing.JScrollPane();
        txaIntermedioQ2Pregunta = new javax.swing.JTextArea();
        lblIntermedioQ2Res = new javax.swing.JLabel();
        btnIntermedioQ2Next1 = new javax.swing.JButton();
        jcbIntermedioQ2Res = new javax.swing.JComboBox<>();
        jpnIntermedioQ3 = new javax.swing.JPanel();
        lblIntermedioQ3Peso1 = new javax.swing.JLabel();
        lblIntermedioQ3Peso2 = new javax.swing.JLabel();
        scrIntermedioQ3 = new javax.swing.JScrollPane();
        txaIntermedioQ3Pregunta = new javax.swing.JTextArea();
        lblIntermedioQ3Res = new javax.swing.JLabel();
        btnIntermedioQ3Next = new javax.swing.JButton();
        jcbIntermedioQ3Res = new javax.swing.JComboBox<>();
        jpnIntermedioQ4 = new javax.swing.JPanel();
        lblIntermedioQ4Peso1 = new javax.swing.JLabel();
        lblIntermedioQ4Peso2 = new javax.swing.JLabel();
        scrIntermedioQ4 = new javax.swing.JScrollPane();
        txaIntermedioQ4Pregunta = new javax.swing.JTextArea();
        lblIntermedioQ4Res = new javax.swing.JLabel();
        btnIntermedioQ4Next = new javax.swing.JButton();
        jcbIntermedioQ4Res = new javax.swing.JComboBox<>();
        jpnIntermedioQ5 = new javax.swing.JPanel();
        lblIntermedioQ5Peso1 = new javax.swing.JLabel();
        lblIntermedioQ5Peso2 = new javax.swing.JLabel();
        scrIntermedioQ5 = new javax.swing.JScrollPane();
        txaIntermedioQ5Pregunta = new javax.swing.JTextArea();
        lbIntermedioQ5Res = new javax.swing.JLabel();
        btnIntermedioQ5Next = new javax.swing.JButton();
        jcbIntermedioQ5Res = new javax.swing.JComboBox<>();
        jpnIntermedioCabecera = new javax.swing.JPanel();
        lblIntermedioUsuario = new javax.swing.JLabel();
        lblIntermedioIntento = new javax.swing.JLabel();
        txbIntermedioDate = new javax.swing.JTextField();
        lblIntermedioNivel = new javax.swing.JLabel();
        txbIntermedioLv1 = new javax.swing.JTextField();
        txbIntermedioLv2 = new javax.swing.JTextField();
        tbxIntermedioLv3 = new javax.swing.JTextField();
        lblIntermedioPuntos = new javax.swing.JLabel();
        txbIntermedioPuntos = new javax.swing.JTextField();
        btnIntermedioRepetir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txbIntermedioIntentos = new javax.swing.JTextField();
        bproJugadorIntermedio = new javax.swing.JProgressBar();
        btnIntermedioSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jugador - Principiante");

        lblIntermedioeQ1Peso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioeQ1Peso.setText("Peso:");

        lblIntermedioQ1Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ1Peso2.setText("1/5");

        txaIntermedioQ1Pregunta.setEditable(false);
        txaIntermedioQ1Pregunta.setColumns(20);
        txaIntermedioQ1Pregunta.setRows(5);
        scrIntermedioQ1.setViewportView(txaIntermedioQ1Pregunta);

        btnIntermedioQ1Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedioQ1Next.setText("Siguiente");

        lblIntermedioQ1Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ1Res.setText("Respuesta");

        jcbIntermedioQ1Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnIntermedioQ1Layout = new javax.swing.GroupLayout(jpnIntermedioQ1);
        jpnIntermedioQ1.setLayout(jpnIntermedioQ1Layout);
        jpnIntermedioQ1Layout.setHorizontalGroup(
            jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ1Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ1Res)
                        .addGap(18, 18, 18)
                        .addComponent(jcbIntermedioQ1Res, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntermedioQ1Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ1Layout.createSequentialGroup()
                        .addGroup(jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioeQ1Peso)
                            .addComponent(lblIntermedioQ1Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrIntermedioQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpnIntermedioQ1Layout.setVerticalGroup(
            jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ1Layout.createSequentialGroup()
                        .addComponent(lblIntermedioeQ1Peso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntermedioQ1Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ1Layout.createSequentialGroup()
                        .addComponent(scrIntermedioQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIntermedioQ1Next)
                        .addComponent(jcbIntermedioQ1Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIntermedioQ1Res))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1).", jpnIntermedioQ1);

        lblIntermedioQ2Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ2Peso1.setText("Peso:");

        lblIntermedioQ2Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ2Peso2.setText("1/5");

        txaIntermedioQ2Pregunta.setEditable(false);
        txaIntermedioQ2Pregunta.setColumns(20);
        txaIntermedioQ2Pregunta.setRows(5);
        scrIntermedioQ2.setViewportView(txaIntermedioQ2Pregunta);

        lblIntermedioQ2Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ2Res.setText("Respuesta");

        btnIntermedioQ2Next1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedioQ2Next1.setText("Siguiente");

        jcbIntermedioQ2Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnIntermedioQ2Layout = new javax.swing.GroupLayout(jpnIntermedioQ2);
        jpnIntermedioQ2.setLayout(jpnIntermedioQ2Layout);
        jpnIntermedioQ2Layout.setHorizontalGroup(
            jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnIntermedioQ2Layout.createSequentialGroup()
                        .addGroup(jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioQ2Peso1)
                            .addComponent(lblIntermedioQ2Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrIntermedioQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnIntermedioQ2Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ2Res)
                        .addGap(18, 18, 18)
                        .addComponent(jcbIntermedioQ2Res, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntermedioQ2Next1)))
                .addGap(24, 24, 24))
        );
        jpnIntermedioQ2Layout.setVerticalGroup(
            jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ2Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ2Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntermedioQ2Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ2Layout.createSequentialGroup()
                        .addComponent(scrIntermedioQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIntermedioQ2Next1)
                        .addComponent(jcbIntermedioQ2Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIntermedioQ2Res))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2).", jpnIntermedioQ2);

        lblIntermedioQ3Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ3Peso1.setText("Peso:");

        lblIntermedioQ3Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ3Peso2.setText("1/5");

        txaIntermedioQ3Pregunta.setEditable(false);
        txaIntermedioQ3Pregunta.setColumns(20);
        txaIntermedioQ3Pregunta.setRows(5);
        scrIntermedioQ3.setViewportView(txaIntermedioQ3Pregunta);

        lblIntermedioQ3Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ3Res.setText("Respuesta");

        btnIntermedioQ3Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedioQ3Next.setText("Siguiente");

        jcbIntermedioQ3Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnIntermedioQ3Layout = new javax.swing.GroupLayout(jpnIntermedioQ3);
        jpnIntermedioQ3.setLayout(jpnIntermedioQ3Layout);
        jpnIntermedioQ3Layout.setHorizontalGroup(
            jpnIntermedioQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnIntermedioQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnIntermedioQ3Layout.createSequentialGroup()
                        .addGroup(jpnIntermedioQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioQ3Peso1)
                            .addComponent(lblIntermedioQ3Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrIntermedioQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnIntermedioQ3Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ3Res)
                        .addGap(18, 18, 18)
                        .addComponent(jcbIntermedioQ3Res, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntermedioQ3Next)))
                .addGap(24, 24, 24))
        );
        jpnIntermedioQ3Layout.setVerticalGroup(
            jpnIntermedioQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIntermedioQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ3Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ3Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntermedioQ3Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ3Layout.createSequentialGroup()
                        .addComponent(scrIntermedioQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnIntermedioQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntermedioQ3Next)
                    .addComponent(jcbIntermedioQ3Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntermedioQ3Res))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3).", jpnIntermedioQ3);

        lblIntermedioQ4Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ4Peso1.setText("Peso:");

        lblIntermedioQ4Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ4Peso2.setText("1/5");

        txaIntermedioQ4Pregunta.setEditable(false);
        txaIntermedioQ4Pregunta.setColumns(20);
        txaIntermedioQ4Pregunta.setRows(5);
        scrIntermedioQ4.setViewportView(txaIntermedioQ4Pregunta);

        lblIntermedioQ4Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ4Res.setText("Respuesta");

        btnIntermedioQ4Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedioQ4Next.setText("Siguiente");

        jcbIntermedioQ4Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnIntermedioQ4Layout = new javax.swing.GroupLayout(jpnIntermedioQ4);
        jpnIntermedioQ4.setLayout(jpnIntermedioQ4Layout);
        jpnIntermedioQ4Layout.setHorizontalGroup(
            jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnIntermedioQ4Layout.createSequentialGroup()
                        .addGroup(jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioQ4Peso1)
                            .addComponent(lblIntermedioQ4Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrIntermedioQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnIntermedioQ4Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ4Res)
                        .addGap(18, 18, 18)
                        .addComponent(jcbIntermedioQ4Res, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntermedioQ4Next)))
                .addGap(24, 24, 24))
        );
        jpnIntermedioQ4Layout.setVerticalGroup(
            jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ4Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ4Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntermedioQ4Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ4Layout.createSequentialGroup()
                        .addComponent(scrIntermedioQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIntermedioQ4Next)
                        .addComponent(jcbIntermedioQ4Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIntermedioQ4Res))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4).", jpnIntermedioQ4);

        lblIntermedioQ5Peso1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ5Peso1.setText("Peso:");

        lblIntermedioQ5Peso2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntermedioQ5Peso2.setText("1/5");

        txaIntermedioQ5Pregunta.setEditable(false);
        txaIntermedioQ5Pregunta.setColumns(20);
        txaIntermedioQ5Pregunta.setRows(5);
        scrIntermedioQ5.setViewportView(txaIntermedioQ5Pregunta);

        lbIntermedioQ5Res.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbIntermedioQ5Res.setText("Respuesta");

        btnIntermedioQ5Next.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedioQ5Next.setText("Finalizar");

        jcbIntermedioQ5Res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnIntermedioQ5Layout = new javax.swing.GroupLayout(jpnIntermedioQ5);
        jpnIntermedioQ5.setLayout(jpnIntermedioQ5Layout);
        jpnIntermedioQ5Layout.setHorizontalGroup(
            jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnIntermedioQ5Layout.createSequentialGroup()
                        .addGroup(jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioQ5Peso1)
                            .addComponent(lblIntermedioQ5Peso2))
                        .addGap(26, 26, 26)
                        .addComponent(scrIntermedioQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnIntermedioQ5Layout.createSequentialGroup()
                        .addComponent(lbIntermedioQ5Res)
                        .addGap(18, 18, 18)
                        .addComponent(jcbIntermedioQ5Res, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntermedioQ5Next)))
                .addGap(24, 24, 24))
        );
        jpnIntermedioQ5Layout.setVerticalGroup(
            jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioQ5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ5Layout.createSequentialGroup()
                        .addComponent(lblIntermedioQ5Peso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntermedioQ5Peso2)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioQ5Layout.createSequentialGroup()
                        .addComponent(scrIntermedioQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIntermedioQ5Next)
                        .addComponent(jcbIntermedioQ5Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbIntermedioQ5Res))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("5).", jpnIntermedioQ5);

        lblIntermedioUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntermedioUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lblIntermedioUsuario.setText("Usuario: bboteo");

        lblIntermedioIntento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntermedioIntento.setForeground(new java.awt.Color(153, 153, 153));
        lblIntermedioIntento.setText("Ultimo Intento:");

        txbIntermedioDate.setEditable(false);
        txbIntermedioDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbIntermedioDate.setForeground(new java.awt.Color(153, 153, 153));
        txbIntermedioDate.setText("dd-mm-yyy, hh:mm");

        lblIntermedioNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntermedioNivel.setText("Nivel Actual: Intermedio");

        txbIntermedioLv1.setEditable(false);
        txbIntermedioLv1.setBackground(new java.awt.Color(255, 255, 0));
        txbIntermedioLv1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbIntermedioLv1.setText("          ");
        txbIntermedioLv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbIntermedioLv1ActionPerformed(evt);
            }
        });

        txbIntermedioLv2.setEditable(false);
        txbIntermedioLv2.setBackground(new java.awt.Color(255, 255, 102));
        txbIntermedioLv2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbIntermedioLv2.setText("          ");
        txbIntermedioLv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbIntermedioLv2ActionPerformed(evt);
            }
        });

        tbxIntermedioLv3.setEditable(false);
        tbxIntermedioLv3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbxIntermedioLv3.setText("          ");
        tbxIntermedioLv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxIntermedioLv3ActionPerformed(evt);
            }
        });

        lblIntermedioPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntermedioPuntos.setText("Ultima Puntuacion");

        txbIntermedioPuntos.setEditable(false);
        txbIntermedioPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbIntermedioPuntos.setForeground(new java.awt.Color(153, 153, 153));

        btnIntermedioRepetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sincronizar.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Reiniciar la Prueba");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Intentos");

        txbIntermedioIntentos.setEditable(false);
        txbIntermedioIntentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txbIntermedioIntentos.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jpnIntermedioCabeceraLayout = new javax.swing.GroupLayout(jpnIntermedioCabecera);
        jpnIntermedioCabecera.setLayout(jpnIntermedioCabeceraLayout);
        jpnIntermedioCabeceraLayout.setHorizontalGroup(
            jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnIntermedioCabeceraLayout.createSequentialGroup()
                        .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioUsuario)
                            .addComponent(lblIntermedioIntento))
                        .addGap(18, 18, 18)
                        .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntermedioNivel)
                            .addComponent(txbIntermedioDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnIntermedioCabeceraLayout.createSequentialGroup()
                        .addComponent(btnIntermedioRepetir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(55, 55, 55)
                .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnIntermedioCabeceraLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txbIntermedioIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioCabeceraLayout.createSequentialGroup()
                            .addComponent(txbIntermedioLv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txbIntermedioLv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tbxIntermedioLv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpnIntermedioCabeceraLayout.createSequentialGroup()
                            .addComponent(lblIntermedioPuntos)
                            .addGap(18, 18, 18)
                            .addComponent(txbIntermedioPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpnIntermedioCabeceraLayout.setVerticalGroup(
            jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIntermedioCabeceraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntermedioUsuario)
                    .addComponent(lblIntermedioNivel)
                    .addComponent(txbIntermedioLv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbIntermedioLv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxIntermedioLv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntermedioIntento)
                    .addComponent(txbIntermedioDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntermedioPuntos)
                    .addComponent(txbIntermedioPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIntermedioRepetir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIntermedioCabeceraLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jpnIntermedioCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txbIntermedioIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bproJugadorIntermedio.setBackground(new java.awt.Color(255, 255, 255));
        bproJugadorIntermedio.setForeground(new java.awt.Color(255, 255, 0));

        btnIntermedioSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedioSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salida.png"))); // NOI18N
        btnIntermedioSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnIntermedioCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bproJugadorIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIntermedioSalir)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnIntermedioCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bproJugadorIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntermedioSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbIntermedioLv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbIntermedioLv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbIntermedioLv1ActionPerformed

    private void txbIntermedioLv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbIntermedioLv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbIntermedioLv2ActionPerformed

    private void tbxIntermedioLv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxIntermedioLv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxIntermedioLv3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJugadorIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJugadorIntermedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar bproJugadorIntermedio;
    public javax.swing.JButton btnIntermedioQ1Next;
    public javax.swing.JButton btnIntermedioQ2Next1;
    public javax.swing.JButton btnIntermedioQ3Next;
    public javax.swing.JButton btnIntermedioQ4Next;
    public javax.swing.JButton btnIntermedioQ5Next;
    public javax.swing.JButton btnIntermedioRepetir;
    public javax.swing.JButton btnIntermedioSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JComboBox<String> jcbIntermedioQ1Res;
    public javax.swing.JComboBox<String> jcbIntermedioQ2Res;
    public javax.swing.JComboBox<String> jcbIntermedioQ3Res;
    public javax.swing.JComboBox<String> jcbIntermedioQ4Res;
    public javax.swing.JComboBox<String> jcbIntermedioQ5Res;
    public javax.swing.JOptionPane jopIntermedioMensaje;
    private javax.swing.JPanel jpnIntermedioCabecera;
    public javax.swing.JPanel jpnIntermedioQ1;
    public javax.swing.JPanel jpnIntermedioQ2;
    public javax.swing.JPanel jpnIntermedioQ3;
    public javax.swing.JPanel jpnIntermedioQ4;
    public javax.swing.JPanel jpnIntermedioQ5;
    private javax.swing.JLabel lbIntermedioQ5Res;
    private javax.swing.JLabel lblIntermedioIntento;
    private javax.swing.JLabel lblIntermedioNivel;
    private javax.swing.JLabel lblIntermedioPuntos;
    private javax.swing.JLabel lblIntermedioQ1Peso2;
    private javax.swing.JLabel lblIntermedioQ1Res;
    private javax.swing.JLabel lblIntermedioQ2Peso1;
    private javax.swing.JLabel lblIntermedioQ2Peso2;
    private javax.swing.JLabel lblIntermedioQ2Res;
    private javax.swing.JLabel lblIntermedioQ3Peso1;
    private javax.swing.JLabel lblIntermedioQ3Peso2;
    private javax.swing.JLabel lblIntermedioQ3Res;
    private javax.swing.JLabel lblIntermedioQ4Peso1;
    private javax.swing.JLabel lblIntermedioQ4Peso2;
    private javax.swing.JLabel lblIntermedioQ4Res;
    private javax.swing.JLabel lblIntermedioQ5Peso1;
    private javax.swing.JLabel lblIntermedioQ5Peso2;
    public javax.swing.JLabel lblIntermedioUsuario;
    private javax.swing.JLabel lblIntermedioeQ1Peso;
    public javax.swing.JScrollPane scrIntermedioQ1;
    public javax.swing.JScrollPane scrIntermedioQ2;
    public javax.swing.JScrollPane scrIntermedioQ3;
    public javax.swing.JScrollPane scrIntermedioQ4;
    public javax.swing.JScrollPane scrIntermedioQ5;
    public javax.swing.JTextField tbxIntermedioLv3;
    public javax.swing.JTextArea txaIntermedioQ1Pregunta;
    public javax.swing.JTextArea txaIntermedioQ2Pregunta;
    public javax.swing.JTextArea txaIntermedioQ3Pregunta;
    public javax.swing.JTextArea txaIntermedioQ4Pregunta;
    public javax.swing.JTextArea txaIntermedioQ5Pregunta;
    public javax.swing.JTextField txbIntermedioDate;
    public javax.swing.JTextField txbIntermedioIntentos;
    public javax.swing.JTextField txbIntermedioLv1;
    public javax.swing.JTextField txbIntermedioLv2;
    public javax.swing.JTextField txbIntermedioPuntos;
    // End of variables declaration//GEN-END:variables
}
